# Import this file into the Fauna graphql playground to define the schema

type TodoItem {
    title: String!
    description: String!
    completed: Boolean!
}

type Query {
    todos: [TodoItem!]!
}